## Base16 Solar Flare
# Author: Chuck Harmston (https://chuck.harmston.ch)

# ===============================
# Super Minimal Bar (Base16)
# ===============================

[theme]
theme = "plain"

[theme.overrides]
idle_bg = "#18262f"
idle_fg = "#a6afb8"
separator_fg = "#667581"
separator_bg = "#18262f"
separator = " • "
[icons]
icons = "material-nf"

# ===============================
# WIFI
# yellow
# ===============================
[[block]]
block = "net"
interval = 3
format = "$icon $ssid"
[block.theme_overrides]
idle_fg = "#e4b51c"

# ===============================
# VOLUME
# red
# ===============================
[[block]]
block = "sound"
driver = "pulseaudio"
#format = "$icon $volume"
[block.theme_overrides]
idle_fg     = "#ef5253"
warning_fg  = "#ef5253"
warning_bg  = "#18262f"

# ===============================
# BATTERY
# green
# ===============================
[[block]]
block = "battery"
interval = 15
format = "$icon $percentage"
full_format = "$icon $percentage"
empty_format = "$icon $percentage"
not_charging_format = "$icon $percentage"
missing_format = "$icon $percentage"
[block.theme_overrides]
idle_bg     = "#18262f"
idle_fg     = "#7cc844"
good_bg     = "#18262f"
good_fg     = "#7cc844"
warning_bg  = "#18262f"
warning_fg  = "#7cc844"
critical_bg = "#18262f"
critical_fg = "#7cc844"

# ===============================
# CALENDAR
# blue
# ===============================
[[block]]
block = "time"
interval = 60
format = "󰃭 $timestamp.datetime(f:'%a %b %d')"
[block.theme_overrides]
idle_fg = "#33b5e1"

# ===============================
# TIME
# magenta
# ===============================
[[block]]
block = "time"
interval = 5
format = "󰥔 $timestamp.datetime(f:'%I:%M %p') "
[block.theme_overrides]
idle_fg = "#a363d5"
