#!/bin/sh

# Description: Add selection or hovered file/directory to cmus queue
#
# Dependencies: mpc, mpd, xdg-user-dir
#
# Notes:
#   1. If adding selection, files/dirs are added in the same order they were selected in nnn
#   2. A new window will be opened if cmus is not running already, playback will start immediately
#   3. If cmus is already running, files will be appended to the queue with no forced playback
#
# Shell: POSIX compliant
# Author: Numair2644@protonmail.com

# (Optional) Set music dir or leave commented out to use OS default
MUSIC_DIR="$(xdg-user-dir MUSIC)"

if ! pgrep -f mpd > /dev/null 2>&1 || [ ! -x "$(command -v mpc)" ]; then
    printf "either mpd is not running or mpc is missing"
    read -r _
    exit 1
fi

selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

fill_queue() {
  dir="$(pwd | sed "s|${MUSIC_DIR}/||")"
  if [ "$REPLY" = "s" ]; then
      xargs < "$selection" -0 mpc add "{$dir}/"
  elif [ -n "$1" ]; then
      mpc add "${dir}/${1}"
  fi
}

# If active selection,then ask what to do
if [ -s "$selection" ]; then
    printf "'c'urrent/'s'el"
    read -r REPLY
fi

fill_queue "$1" && printf "successfully added to mpd queue:\n"
read -r _

# Clear selection
if [ -p "$NNN_PIPE" ]; then
    printf "-" > "$NNN_PIPE"
fi
