border-size=1
anchor=top-right
dpi-aware=no
icon-theme=Papirus
max-icon-size=32
progress-bar-height=20
selection-helper=dmenu

# Fonts
title-font=monospace:size=14
summary-font=monospace:size=14
body-font=monospace:size=14

# Timeout values are in seconds. 0 to disable
max-timeout=0
default-timeout=8
idle-timeout=0

# Sizing
max-height=200
max-width=400
padding-vertical=10
padding-horizontal=20

# Tinty Start
## Base16 Solar Flare
# Author: Chuck Harmston (https://chuck.harmston.ch)

background=18262fff
border-color=33b5e1ff
title-color=a6afb8ff
summary-color=a6afb8ff
body-color=a6afb8ff
progress-bar-color=33b5e1ff

[low]
background=18262fff
border-color=33b5e1ff
title-color=a6afb8ff
summary-color=a6afb8ff
body-color=a6afb8ff
progress-bar-color=33b5e1ff

[critical]
background=18262fff
border-color=33b5e1ff
title-color=a6afb8ff
summary-color=a6afb8ff
body-color=a6afb8ff
progress-bar-color=33b5e1ff
# Tinty End
