#!/bin/sh

# Fuzzel config script
# Defines appearance and behavior

font=monospace:size=9.0
dpi-aware=yes
prompt="󰍉 "
icons-enabled=no
show-actions=yes
lines=8
width=40
horizontal-pad=20
vertical-pad=6
line-height=20

# Tinty Start
## Base16 Solar Flare
# Author: Chuck Harmston (https://chuck.harmston.ch)
[colors]
background="18262fff"
text="a6afb8ff"
match="e4b51cff"
selection="33b5e1ff"
selection-text="18262fff"
selection-match="ef5253ff"
border="33b5e1ff"
# Tinty End

[border]
width=1
radius=10
