# Commands go through /bin/sh (default)
shell = "sh -c '{}'"

[[item]]
file = "~/.config/sway/config"
template = "sway"
subtemplate = "colors"
hook = "swaymsg reload"
light = false

[[item]]
file = "~/.config/bash/base16-shell"
template = "shell"
rewrite = true
hook = "pkill -USR1 bash"

[[item]]
file = "~/.config/swaylock/config"
template = "swaylock"

#[[item]]
#file = "~/.config/swaynag/config"
#template = "swaynag"
#subtemplate = "colors"

[[item]]
file = "~/.config/i3blocks/config"
template = "i3blocks"
subtemplate = "config"
rewrite = true

[[item]]
file = "~/.config/mako/config"
template = "mako"
hook = "makoctl reload"

[[item]]
file = "~/.config/wob/wob.ini"
template = "wob"

[[item]]
file = "~/.config/fuzzel/fuzzel.ini"
template = "fuzzel"

[[item]]
file = "~/.config/nvim/pack/bundle/opt/base16-vim/colors/base16.vim"
template = "vim"
rewrite = true

[[item]]
file = "~/.config/kak/colors/base16.kak"
template = "kakoune"
rewrite = true

[[item]]
file = "~/.config/bash/bashrc.d/base16-fzf"
template = "fzf"
rewrite = true

[[item]]
file = "~/.config/cava/config"
template = "cava"
subtemplate = "gradient"

[[item]]
file= "~/.config/zathura/zathurarc"
template = "zathura"

[[item]]
file = "~/.config/qutebrowser/theme.py"
template = "qutebrowser"
subtemplate = "minimal"
rewrite = true
hook = "pgrep -x 'qutebrowser' && qutebrowser :config-source"

[[item]]
file = "~/.config/godot/text_editor_themes/base16.tres"
template = "godot"
rewrite = true
